#!/usr/bin/env node
// Generates Rust FFI stubs from bloom's package.json manifest.
// Output: src/ffi_stubs.rs — all bloom_* functions as #[no_mangle] stubs.
// Functions implemented elsewhere in lib.rs (the override list) are skipped.

const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'package.json'), 'utf8'));
const fns = pkg.perry.nativeLibrary.functions;

const OVERRIDES = new Set([
  // Platform + input
  'bloom_get_platform', 'bloom_get_crown_rotation', 'bloom_get_language',
  'bloom_set_direct_2d_mode',
  'bloom_get_screen_width', 'bloom_get_screen_height',
  'bloom_get_touch_x', 'bloom_get_touch_y', 'bloom_get_touch_count',
  'bloom_get_delta_time', 'bloom_get_time', 'bloom_get_fps',
  'bloom_init_window', 'bloom_close_window', 'bloom_window_should_close',
  'bloom_begin_drawing', 'bloom_end_drawing', 'bloom_clear_background',
  'bloom_run_game', 'bloom_is_any_input_pressed',
  'bloom_is_key_pressed', 'bloom_is_key_down', 'bloom_is_key_released',
  'bloom_set_target_fps',
  'bloom_inject_key_down', 'bloom_inject_key_up',
  'bloom_inject_gamepad_axis', 'bloom_inject_gamepad_button_down', 'bloom_inject_gamepad_button_up',
  'bloom_is_gamepad_available', 'bloom_get_gamepad_axis',
  'bloom_is_gamepad_button_pressed', 'bloom_is_gamepad_button_down', 'bloom_is_gamepad_button_released',
  'bloom_get_gamepad_axis_count',
  // 2D camera + shapes
  'bloom_begin_mode_2d', 'bloom_end_mode_2d',
  'bloom_draw_rect', 'bloom_draw_rect_lines',
  'bloom_draw_circle', 'bloom_draw_circle_lines',
  'bloom_draw_line', 'bloom_draw_triangle', 'bloom_draw_poly',
  // Textures
  'bloom_load_texture', 'bloom_unload_texture',
  'bloom_get_texture_width', 'bloom_get_texture_height',
  'bloom_draw_texture', 'bloom_draw_texture_rec', 'bloom_draw_texture_pro',
  'bloom_set_texture_filter',
  // Text
  'bloom_draw_text', 'bloom_draw_text_ex',
  'bloom_measure_text', 'bloom_measure_text_ex',
  'bloom_load_font', 'bloom_unload_font',
  // File I/O
  'bloom_file_exists', 'bloom_read_file', 'bloom_write_file',
  // 3D immediate-mode
  'bloom_begin_mode_3d', 'bloom_end_mode_3d',
  'bloom_draw_cube', 'bloom_draw_cube_wires',
  'bloom_draw_sphere', 'bloom_draw_sphere_wires',
  'bloom_draw_cylinder', 'bloom_draw_plane', 'bloom_draw_grid',
  // Audio
  'bloom_init_audio', 'bloom_close_audio',
  'bloom_load_sound', 'bloom_play_sound', 'bloom_play_sound_ex', 'bloom_stop_sound', 'bloom_unload_sound',
  'bloom_set_sound_volume', 'bloom_set_master_volume', 'bloom_play_sound_3d',
  'bloom_load_music', 'bloom_play_music', 'bloom_stop_music', 'bloom_unload_music',
  'bloom_update_music_stream', 'bloom_set_music_volume', 'bloom_is_music_playing',
  // Retained scene graph
  'bloom_scene_create_node', 'bloom_scene_destroy_node',
  'bloom_scene_set_visible', 'bloom_scene_set_cast_shadow', 'bloom_scene_set_receive_shadow',
  'bloom_scene_set_parent', 'bloom_scene_set_transform', 'bloom_scene_update_geometry',
  'bloom_scene_set_material_color', 'bloom_scene_set_material_pbr', 'bloom_scene_set_material_texture',
  'bloom_scene_node_count', 'bloom_scene_get_transform',
  'bloom_add_directional_light', 'bloom_add_point_light',
  // Models
  'bloom_load_model', 'bloom_gen_mesh_cube', 'bloom_scene_attach_model',
  // Post-FX
  'bloom_enable_postfx', 'bloom_disable_postfx',
  'bloom_set_vignette', 'bloom_set_chromatic_aberration', 'bloom_set_film_grain',
  'bloom_set_manual_exposure', 'bloom_set_auto_exposure', 'bloom_set_sun_shafts',
]);

const rustType = (p) => {
  if (p === 'f64') return 'f64';
  if (p === 'i64') return 'i64';
  // Perry passes/returns heap strings as a pointer carried in an integer
  // register; the stub ignores it, so i64 is the correct ABI-compatible type.
  if (p === 'string') return 'i64';
  if (p === 'void') return '()';
  throw new Error(`Unknown param type: ${p}`);
};

const defaultForReturn = (r) => {
  if (r === 'f64') return '0.0';
  if (r === 'i64') return '0';
  if (r === 'string') return '0';
  if (r === 'void') return '()';
  throw new Error(`Unknown return type: ${r}`);
};

let out = '// Auto-generated by gen_stubs.js — do not edit by hand.\n';
out += '// All non-overridden bloom_* FFI functions as no-op stubs.\n';
out += '// The watchOS proof-of-life crate implements only the input / platform\n';
out += '// surface; rendering calls are intentionally no-ops pending the wgpu/Metal\n';
out += '// dlopen work.\n\n';
out += '#![allow(unused_variables, non_snake_case)]\n\n';

let skipped = 0;
for (const fn of fns) {
  if (OVERRIDES.has(fn.name)) { skipped++; continue; }
  const params = fn.params.map((p, i) => `_p${i}: ${rustType(p)}`).join(', ');
  const ret = fn.returns === 'void' ? '' : ` -> ${rustType(fn.returns)}`;
  const body = fn.returns === 'void' ? '' : `    ${defaultForReturn(fn.returns)}\n`;
  out += `#[no_mangle] pub extern "C" fn ${fn.name}(${params})${ret} {\n${body}}\n`;
}

fs.writeFileSync(path.join(__dirname, 'src', 'ffi_stubs.rs'), out);
console.error(`Wrote ${fns.length - skipped} stubs to src/ffi_stubs.rs (skipped ${skipped} overrides)`);
