export const UiBackend = {
  Egui: 0,
  DearImGui: 1,
} as const;

export const UiOpcode = {
  BeginWindow: 1,
  EndWindow: 2,
  BeginPanel: 3,
  EndPanel: 4,
  BeginHorizontal: 5,
  EndHorizontal: 6,
  BeginVertical: 7,
  EndVertical: 8,
  SetWindowPosition: 9,
  SetWindowSize: 10,
  Spacing: 11,
  Separator: 12,
  Label: 13,
  Link: 14,
  Button: 15,
  Checkbox: 16,
  RadioButton: 17,
  SliderFloat: 18,
  SliderInt: 19,
  DragFloat: 20,
  TextEdit: 21,
  Combo: 22,
  Selectable: 23,
  CollapsingHeader: 24,
  BeginScrollArea: 25,
  EndScrollArea: 26,
  BeginTabBar: 27,
  EndTabBar: 28,
  BeginTabItem: 29,
  EndTabItem: 30,
  ProgressBar: 31,
  Image: 32,
  PaintLine: 33,
  PaintRect: 34,
  PaintCircle: 35,
  PaintText: 36,
  PaintPolyline: 37,
  PaintPolygon: 38,
  SetStyle: 39,
  LoadFont: 40,
  RegisterTexture: 41,
  BeginMenuBar: 42,
  EndMenuBar: 43,
  BeginMenu: 44,
  EndMenu: 45,
  MenuItem: 46,
  TreeNode: 47,
  TreePop: 48,
  BeginTable: 49,
  EndTable: 50,
  TableNextRow: 51,
  TableNextColumn: 52,
  PlotLines: 53,
  DemoWindow: 54,
  MetricsWindow: 55,
  EndCombo: 56,
  EndCollapsingHeader: 57,
} as const;

export type UiBackendId = typeof UiBackend[keyof typeof UiBackend];
