// Auto-generated by gen_stubs.js — do not edit by hand.
// All non-overridden bloom_* FFI functions as no-op stubs.
// Platform and Colyseus calls are implemented by the watchOS crate;
// rendering calls remain no-ops pending the wgpu/Metal dlopen work.

#![allow(unused_variables, non_snake_case)]

#[no_mangle] pub extern "C" fn bloom_attach_native(_p0: i64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_attach_hwnd(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_resize(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_ui_command(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ui_scratch_reset(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_ui_scratch_push_f64(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_ui_scratch_command(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ui_inject_text(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_ui_response(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ui_response_text(_p0: f64, _p1: f64) -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_ui_is_available(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ui_wants_input(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ui_take_keyboard_request(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_take_screenshot(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_set_env_clear_from_hdr(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_is_key_repeated(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_is_mouse_button_pressed(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_is_mouse_button_down(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_is_mouse_button_released(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_listener_position(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_play_sound_3d_ex(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_voice_set_position(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_voice_stop(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_voice_set_volume(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_voice_set_pitch(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_voice_set_lowpass(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_load_image(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_image_resize(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_image_crop(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_image_flip_h(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_image_flip_v(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_load_texture_from_image(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_gen_texture_mipmaps(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_draw_ray(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64) {
}
#[no_mangle] pub extern "C" fn bloom_draw_model(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64) {
}
#[no_mangle] pub extern "C" fn bloom_draw_model_rotated(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_draw_model_transform16(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64, _p13: f64, _p14: f64, _p15: f64, _p16: f64, _p17: f64) {
}
#[no_mangle] pub extern "C" fn bloom_unload_model(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_gen_mesh_heightmap(_p0: f64, _p1: f64, _p2: f64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_load_shader(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_compile_material(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_compile_material_refractive(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_compile_material_transparent(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_compile_material_additive(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_compile_material_cutout(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_compile_material_instanced(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_create_instance_buffer_scratch(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_material_params_scratch(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_compile_material_from_file(_p0: i64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_splat_impulse(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_profiler_overlay_text() -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_profiler_frame_history() -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_profiler_row_count() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_profiler_row_label(_p0: f64) -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_profiler_row_cpu_us(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_profiler_row_gpu_us(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_profiler_hist_count() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_profiler_hist_cpu_us(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_profiler_hist_gpu_us(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_create_instance_buffer(_p0: i64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_submit_material_draw_instanced(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_destroy_instance_buffer(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_create_planar_reflection(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_material_reflection_probe(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_create_texture_array(_p0: i64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_create_texture_array_ex(_p0: i64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_create_texture_array_scratch(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_material_texture_array(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_material_shading_model(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_material_probe_visible(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_material_foliage(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_post_pass(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_clear_post_pass() {
}
#[no_mangle] pub extern "C" fn bloom_add_post_pass(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_clear_all_post_passes() {
}
#[no_mangle] pub extern "C" fn bloom_draw_material(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64) {
}
#[no_mangle] pub extern "C" fn bloom_load_model_animation(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_instantiate_animation(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_update_model_animation(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) {
}
#[no_mangle] pub extern "C" fn bloom_anim_play(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_anim_set_layer(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_anim_set_root_motion(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_anim_update(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_anim_finished(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_anim_clip_duration(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_anim_root_delta(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_model_find_joint(_p0: f64, _p1: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_model_joint_world(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_create_texture_array_from_files(_p0: i64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_compile_material_instanced_bucket(_p0: i64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ragdoll_create() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ragdoll_activate(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ragdoll_push(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_ragdoll_update(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_ragdoll_release(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_particles_create(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_particles_configure(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_particles_emit(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) {
}
#[no_mangle] pub extern "C" fn bloom_particles_update(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_particles_instance_buffer(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_particles_clear(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_particles_live(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_decals_init(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_decals_spawn(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) {
}
#[no_mangle] pub extern "C" fn bloom_decals_set_style(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_decals_update(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_decals_instance_buffer() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_decals_clear() {
}
#[no_mangle] pub extern "C" fn bloom_create_mesh(_p0: i64, _p1: f64, _p2: i64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_mesh_scratch_reset() {
}
#[no_mangle] pub extern "C" fn bloom_mesh_scratch_push_f32(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_mesh_scratch_push_u32(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_create_mesh_scratch(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_joint_test(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ambient_light(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_directional_light(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_procedural_sky(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sun_direction(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_fog(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sharpen_strength(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_present_mode(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_taa_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_occlusion_culling(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_render_scale(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_get_render_scale() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_upscale_mode(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_cas_strength(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_get_physical_width() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_physical_height() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_auto_resolution(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_env_intensity(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssgi_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_path_tracing(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_path_tracing_supported() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_ssgi_intensity(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssgi_radius(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_dof(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_quality_preset(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_shadows_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_shadows_always_fresh(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_bloom_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_bloom_intensity(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_tonemap(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_auto_exposure_key(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_auto_exposure_rate(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssao_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssao_intensity(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssao_radius(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_wind(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_launch_process(_p0: i64, _p1: i64, _p2: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_output_scale(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_get_output_scale() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_model_foliage_wind(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_foliage_shadow_motion(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_cloud_shadows(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssr_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_motion_blur_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sss_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_profiler_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_get_profiler_frame_cpu_us() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_profiler_frame_gpu_us() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_print_profiler_summary() {
}
#[no_mangle] pub extern "C" fn bloom_get_model_mesh_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_material_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_sound_bus(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sound_reverb_send(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sound_lowpass(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_bus_gain(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_duck_bus(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_reverb(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_gamepad_rumble(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_toggle_fullscreen() {
}
#[no_mangle] pub extern "C" fn bloom_set_window_title(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_set_window_icon(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_disable_cursor() {
}
#[no_mangle] pub extern "C" fn bloom_enable_cursor() {
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_delta_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_delta_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_wheel() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_char_pressed() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_min_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_min_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_min_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_max_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_max_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_max_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_register_frame_callback(_p0: f64, _p1: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_unregister_frame_callback(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_gi_only(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_trs(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_transform16(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64, _p13: f64, _p14: f64, _p15: f64, _p16: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_update_geometry_scratch(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_lod(_p0: f64, _p1: f64, _p2: i64, _p3: f64, _p4: i64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_attach_model_lod(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_node_vertex_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_node_index_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_cursor_shape(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_clipboard_text(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_get_clipboard_text() -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_open_file_dialog(_p0: i64, _p1: i64) -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_save_file_dialog(_p0: i64, _p1: i64) -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_scene_pick_all(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_all_handle(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_all_distance(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_set_material_water(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_gen_mesh_spline_ribbon(_p0: i64, _p1: f64, _p2: i64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_gen_mesh_spline_ribbon_scratch(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_load_render_texture(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_unload_render_texture(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_begin_texture_mode(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_end_texture_mode() {
}
#[no_mangle] pub extern "C" fn bloom_get_render_texture_texture(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_min_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_min_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_min_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_max_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_max_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_max_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_set_user_data(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_get_user_data(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_extrude_polygon(_p0: f64, _p1: i64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_subtract_box(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_enable_shadows() {
}
#[no_mangle] pub extern "C" fn bloom_disable_shadows() {
}
#[no_mangle] pub extern "C" fn bloom_dump_shadow_map(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_selected(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_hovered(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_outline_color(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_outline_thickness(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_project_to_screen(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_project_screen_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_pick(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_handle() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_distance() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_z() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_normal_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_normal_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_normal_z() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_stage_texture(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_stage_model(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_stage_sound(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_texture(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_model(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_sound(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_music(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_create_world(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_destroy_world(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_gravity(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_get_gravity(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_optimize_broadphase(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_step(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_step_fixed(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_set_fixed_timestep(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_interpolation(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_get_step_alpha(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_set_layer_collides(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_get_layer_collides(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_active_body_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_box(_p0: f64, _p1: f64, _p2: f64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_sphere(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_capsule(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_cylinder(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_scaled(_p0: f64, _p1: f64, _p2: f64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_offset_com(_p0: f64, _p1: f64, _p2: f64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_release(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_scratch_reset() {
}
#[no_mangle] pub extern "C" fn bloom_physics_scratch_push_f32(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_scratch_push_u32(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_convex_hull(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_mesh(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_heightfield(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_compound_begin() {
}
#[no_mangle] pub extern "C" fn bloom_physics_compound_add_child(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_compound_end() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_bounds(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_shape_volume(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_create(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_destroy(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_activate(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_deactivate(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_is_active(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_is_valid(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_position(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_rotation(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_position(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_rotation(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_transform(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_move_kinematic(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_linear_velocity(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_angular_velocity(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_point_velocity(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_linear_velocity(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_angular_velocity(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_add_force(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_add_impulse(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_add_torque(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_add_angular_impulse(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_add_force_at(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_add_impulse_at(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_friction(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_restitution(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_linear_damping(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_angular_damping(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_gravity_factor(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_ccd(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_motion_type(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_object_layer(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_is_sensor(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_allow_sleeping(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_shape(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_lock_rotation_axes(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_lock_translation_axes(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_mass(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_friction(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_restitution(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_object_layer(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_body_set_user_data(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_body_get_user_data(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_raycast(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_raycast_all(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_count() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_body(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_axis(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_fraction(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_sub_shape(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_overlap_sphere(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_overlap_point(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_overlap_box(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_overlap_body(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_constraint_fixed(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_constraint_point(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_constraint_hinge(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64, _p13: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_constraint_slider(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64, _p13: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_constraint_distance(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_constraint_destroy(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_constraint_set_enabled(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_contact_count() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_contact_field(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_clear_contacts(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_character_create(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64, _p13: f64, _p14: f64, _p15: f64, _p16: f64, _p17: f64, _p18: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_destroy(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_character_update(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_character_get_position(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_get_rotation(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_set_position(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_character_set_rotation(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_character_get_linear_velocity(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_set_linear_velocity(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_character_get_ground_state(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_get_ground_normal(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_get_ground_position(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_get_ground_body(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_character_set_shape(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_soft_body_create(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64, _p13: f64, _p14: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_soft_body_vertex_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_soft_body_get_vertex(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_soft_body_set_vertex(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_soft_body_set_vertex_inv_mass(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_vehicle_create(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64, _p10: f64, _p11: f64, _p12: f64, _p13: f64, _p14: f64, _p15: f64, _p16: f64, _p17: f64, _p18: f64, _p19: f64, _p20: f64, _p21: f64, _p22: f64, _p23: f64, _p24: f64, _p25: f64, _p26: f64, _p27: f64, _p28: f64, _p29: f64, _p30: f64, _p31: f64, _p32: f64, _p33: f64, _p34: f64, _p35: f64, _p36: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_vehicle_destroy(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_vehicle_get_chassis(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_vehicle_set_input(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_vehicle_get_wheel_transform(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_vehicle_get_engine_rpm(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_vehicle_get_wheel_angular_velocity(_p0: f64, _p1: f64) -> f64 {
    0.0
}
