export { Game } from './core/game';
export type { GameOptions, GameRenderMode, EmbeddedFrameCallbacks, GameDebugOptions, GameStats } from './core/game';
export { ScriptRuntime, ScriptComponent, DEFAULT_SCRIPT_LIMITS } from './scripting';
export type { ScriptComponentOptions, ScriptContext, ScriptLimits, ScriptPermission, ScriptStatus } from './scripting';
export { Window, Renderer } from './core';
export type { WindowMode, WindowOptions, UpscaleMode, RendererStats } from './core';
export { ColorConstants, Colors, Key, MouseButton, CursorShape, Platform, QualityPreset, Tonemap } from './core';
export type {
  Color,
  Rect,
  Vector2DLike,
  Camera2D,
  Camera3D,
  Ray,
  BoundingBox,
  RayHit,
  FrustumPlanes,
  Mat4,
} from './core/types';

export { Vector2D, Vec3, Vec4, Quat, Matrix4, Mathf, Collision } from './math';
export type { Matrix4Array } from './math';

export { Texture, ImageData, RenderTexture, FILTER_LINEAR, FILTER_NEAREST } from './textures';
export { AssetManager, SceneAssetManager, AssetGroup } from './assets';
export type {
  AssetGroupAsset,
  AssetGroupEntryResult,
  AssetGroupEntryState,
  AssetGroupKind,
  AssetGroupState,
} from './assets';
export {
  SpriteSheet,
  SpriteRenderer,
  SpriteAnimation,
  SpriteAnimator,
  ParticleEmitter2D,
  SPRITE_ANIMATION_TEMPLATE_FORMAT,
  SPRITE_ANIMATION_TEMPLATE_VERSION,
  validateSpriteAnimationTemplate,
  validateSpriteAnimationTemplateBinding,
  SpriteAnimationTemplateAsset,
  SpriteAnimationTemplateBoundAnimation,
  SpriteAnimationTemplateBoundClip,
  SpriteAnimationTemplateRenderer,
} from './sprites';
export type {
  SpriteFrame,
  SpriteFrameDefinition,
  SpriteFrameTrim,
  SpriteFrameTrimDefinition,
  SpriteSheetOptions,
  SpriteRendererOptions,
  ResolvedSpriteKeyframe,
  SpriteAnimationLoop,
  SpriteAnimationOptions,
  SpriteKeyframe,
  SpriteAnimationPlaybackClip,
  SpriteAnimationPlaybackFrame,
  SpriteAnimationTemplateBindingFailure,
  SpriteAnimationTemplateBindingResult,
  SpriteAnimationTemplateBindingSuccess,
  SpriteAnimationTemplateBoundFrame,
  SpriteAnimationTemplateBoundLayer,
  SpriteAnimationTemplateRendererOptions,
  ResolvedSpriteAnimationTemplate,
  ResolvedSpriteAnimationTemplateClip,
  ResolvedSpriteAnimationTemplateFrame,
  ResolvedSpriteAnimationTemplateLayer,
  SpriteAnimationTemplate,
  SpriteAnimationTemplateBindingValidationResult,
  SpriteAnimationTemplateCanvasSize,
  SpriteAnimationTemplateClip,
  SpriteAnimationTemplateDiagnostic,
  SpriteAnimationTemplateFrame,
  SpriteAnimationTemplateImageSize,
  SpriteAnimationTemplateLayer,
  SpriteAnimationTemplateLoop,
  SpriteAnimationTemplateParameter,
  ResolvedSpriteAnimationTemplateTransform,
  SpriteAnimationTemplateSourceRect,
  SpriteAnimationTemplateTransform,
  SpriteAnimationTemplateValidationResult,
  SpriteAnimationTemplateVector2,
  SpriteAnimationTransition,
  SpriteAnimatorOptions,
  SpriteAnimatorState,
  SpriteCompleteCallback,
  SpriteMarkerCallback,
  SpriteNumberComparison,
  SpritePlayOptions,
  SpriteStateChangedCallback,
  SpriteTransitionCondition,
  ParticleBurstOptions,
  ParticleEmitter2DOptions,
  ParticleEmitterShape,
  ParticleRange,
} from './sprites';
export { Font } from './text';
export { Model, Mesh, Material, Animation } from './models';
export type { MaterialKind, DrawCubeOpts, ProceduralSkyOptions } from './models';
export {
  BUCKET_ADDITIVE,
  BUCKET_CUTOUT,
  BUCKET_OPAQUE,
  BUCKET_TRANSPARENT,
  PROFILE_OPAQUE,
  PROFILE_TRANSLUCENT,
  SHADING_MODEL_DEFAULT_LIT,
  SHADING_MODEL_FOLIAGE,
  SHADING_MODEL_SUBSURFACE,
  TEX_ARRAY_FORMAT_LINEAR,
  TEX_ARRAY_FORMAT_SRGB,
  TEXTURE_ARRAY_ALBEDO,
  TEXTURE_ARRAY_MR,
  TEXTURE_ARRAY_NORMAL,
} from './models';

export {
  AudioSystem,
  AudioListener2D,
  AudioEmitter2D,
  Sound,
  StagedSound,
  Music,
  StagedMusic,
  SoundManager,
} from './audio';
export type {
  SoundPlayOptions,
  SoundVoice,
  SpatialPlaybackOptions,
  ManagedMusicOptions,
  ManagedSoundOptions,
  SpatialSoundOptions,
  AudioEmitter2DOptions,
} from './audio';
export { BUS_SFX, BUS_MUSIC, BUS_UI } from './audio';

export {
  GameComponent,
  GameObject,
  GameScene,
  Scene,
  SceneManager,
  Transform,
  SceneNodeComponent,
  RigidBodyComponent,
  AudioSourceComponent,
} from './game';
export type {
  GameComponentType,
  GameObjectOptions,
  ParentOptions,
  SceneState,
  SceneOptions,
  SceneOwnedResource,
  SceneStats,
  TransformOptions,
  TransformTRS,
  SceneNodeComponentOptions,
  RigidBodyMotionType,
  RigidBodyComponentOptions,
  AudioSourceComponentOptions,
} from './game';
export { SceneGraph, SceneNode, FrameSubscription } from './scene';
export type { ScenePickEntry, ScenePickHit, SceneNodeOptions, PbrMaterial } from './scene';

export { InputSystem, InputActionMap } from './input';
export type {
  ActionAxisBinding,
  ActionButtonBinding,
  InputActionMapActionData,
  InputActionMapAxisData,
  InputActionMapData,
} from './input';
export {
  GameDatabase,
  DatabaseTransaction,
  columns,
  defineTable,
  defineSchema,
  defineMigration,
  MigrationBuilder,
} from './storage';
export type {
  DatabaseResult,
  DatabaseStatus,
  DatabaseFailureStatus,
  DatabaseState,
  GameDatabaseOptions,
  ColumnDescriptor,
  ColumnOptions,
  ColumnKind,
  ColumnValue,
  TableDescriptor,
  IndexDescriptor,
  DatabaseSchema,
  DatabaseRow,
  DatabaseInsert,
  DatabaseUpdate,
  Comparison,
  DatabaseFilter,
  DatabaseOrder,
  DatabaseSelect,
  DatabaseMigration,
  MigrationStep,
} from './storage';
export { PhysicsWorld2D, PhysicsBody2D, CharacterBody2D } from './physics2d';
export type {
  PhysicsBody2DOptions,
  PhysicsBodyContact2D,
  PhysicsBodyType2D,
  PhysicsContact2D,
  PhysicsContactPhase2D,
  PhysicsShape2D,
  PhysicsQueryOptions2D,
  PhysicsRayHit2D,
  PhysicsWorld2DOptions,
  CharacterBody2DOptions,
} from './physics2d';
export { Tilemap } from './tilemap';
export type { TilemapCellFlip, TilemapOptions, TilemapSolidTile, TilemapTileDefinition } from './tilemap';
export { CameraRig2D, ParallaxLayer2D, Viewport2D, getParallaxOffset } from './camera2d';
export type {
  Camera2DSnapshot,
  CameraRig2DOptions,
  CameraShake2DOptions,
  ParallaxLayer2DOptions,
  Viewport2DOptions,
  ViewportScalingMode2D,
  ViewportTransform2D,
} from './camera2d';
export { AStarGrid2D, ASTAR_GRID_2D_MAX_CELLS } from './pathfinding2d';
export type { AStarGrid2DOptions, GridPoint2D } from './pathfinding2d';
export {
  PhysicsWorld,
  Collider,
  BoxCollider,
  SphereCollider,
  CapsuleCollider,
  CylinderCollider,
  ConvexHullCollider,
  MeshCollider,
  HeightfieldCollider,
  CompoundCollider,
  ScaledCollider,
  OffsetCollider,
  RigidBody,
  Joint,
  CharacterController,
  GroundState,
  SoftBody,
  Vehicle,
  MotionType,
  ContactEvent,
  Layer,
  MAX_OBJECT_LAYERS,
  ALL_LAYERS_MASK,
} from './physics';
export type {
  PhysicsWorldOptions,
  PhysicsStepHooks,
  PhysicsRayHit,
  PhysicsContact,
  PhysicsTransform,
  CompoundColliderChild,
  RigidBodyOptions,
  JointKind,
  JointOptions,
  CharacterControllerOptions,
  VehicleOptions,
  WorldConfig,
  BodyConfig,
  SoftBodyConfig,
} from './physics';

export { WorldData, WorldInstance, PrefabLibrary, WORLD_SCHEMA_VERSION } from './world';
export type {
  WorldInstantiateOptions,
  WorldEntityNode,
  WorldDocument,
  LightData,
  Bounds,
  EnvironmentData,
  TerrainData,
  TerrainLayer,
  EntityData,
  TransformData,
  WaterVolume,
  RiverSpline,
  PrefabData,
  PrefabChild,
  SaveResult,
  ValidationResult,
  TerrainRaycastHit,
  PrefabLeaf,
  Vec3Lit,
  Vec4Lit,
  Mat4Lit,
} from './world';

export {
  WORLD2D_FORMAT,
  WORLD2D_VERSION,
  BUILTIN_WORLD2D_COMPONENT_KINDS,
  validateWorld2D,
  formatWorld2DDiagnostics,
  normalizeWorld2DStorage,
  migrateWorld2D,
  serializeWorld2D,
  World2DComponentRegistry,
  World2DLoader,
} from './world2d';
export type {
  World2DJsonValue,
  World2DVector,
  World2DRect,
  World2DPropertyData,
  WorldProperty,
  World2DTileDefinition,
  World2DTilesetData,
  WorldTileCell,
  World2DTileCell,
  World2DComponentDescriptor,
  World2DSpriteRendererData,
  World2DPhysicsShape,
  World2DPhysicsBodyData,
  World2DLayerBase,
  World2DTileLayer,
  World2DObjectData,
  World2DObjectLayer,
  World2DLayer,
  World2DDocument,
  World2DDiagnostic,
  World2DValidationResult,
  World2DMigrationResult,
  World2DLoadInstance,
  World2DLoadResult,
  World2DSerializeResult,
  World2DComponentFactoryValue,
  World2DComponentFactoryContext,
  World2DComponentFactory,
  World2DLoaderOptions,
  World2DSerializeMode,
  World2DSerializeEffort,
  World2DSerializeOptions,
  World2DTuple2,
  World2DTuple4,
  World2DStoredTileGrid,
  World2DStoredTileDefinition,
  World2DStoredTileset,
  World2DStoredObject,
  World2DStoredLayerBase,
  World2DStoredTileLayer,
  World2DStoredObjectLayer,
  World2DStoredLayer,
  World2DStorageV2,
} from './world2d';

export { TouchControls, VirtualJoystick, VirtualButton } from './mobile';
export type { VirtualJoystickOptions, VirtualButtonOptions } from './mobile';
export { ParticleSystem, DecalSystem, SceneVfx } from './vfx';
export type { ParticleConfig, ParticleEmitOptions, DecalStyle } from './vfx';
export { SeededRandom, Noise2D } from './procedural';
export type { FractalNoiseOptions } from './procedural';
export { Ui, UiBackend, UiOpcode } from './ui';
export { DebugUi } from './debug-ui';
export type { UiApi, UiId, UiResponse, UiColor } from './ui';
export {
  GUI,
  GUIManager,
  GUIEvent,
  GUIEventType,
  GuiProfile,
  GUIProfiles,
  GuiControlKind,
  GuiNativeBridge,
  GuiOpcode,
  GuiEventField,
  GuiWindow,
  GuiPanel,
  GuiScroll,
  GuiBitmapBorder,
  GuiStretch,
  GuiFrameSet,
  GuiButtonBase,
  GuiButton,
  GuiCheckBox,
  GuiRadioButton,
  GuiBitmapButton,
  GuiSlider,
  GuiText,
  GuiMLText,
  GuiTextEdit,
  GuiMLTextEdit,
  GuiTextEditSlider,
  GuiArray,
  GuiPopUpMenu,
  GuiPopUpEdit,
  GuiTreeView,
  GuiTextList,
  GuiTab,
  GuiMenu,
  GuiContextMenu,
  GuiBitmap,
  GuiShowImg,
  GuiProgress,
  GuiDrawingPanel,
  GUI_TREE_MAX_PATH_LENGTH,
  GUI_TREE_MAX_PATH_SEGMENTS,
} from './gui';
export type {
  GUIEventOptions,
  GUIEventTypeCode,
  GUIControlOptions,
  GuiCursor,
  GuiPoint,
  GuiRect,
  GuiSize,
  GuiNativeApi,
  GuiNativeResponse,
  GuiNativeEvent,
  GuiOpcodeCode,
  GuiEventFieldCode,
  GuiControlItemCommand,
  GuiDrawingPayload,
  GuiProfileOptions,
  GuiFontProfile,
  GuiAlignmentProfile,
  GuiSpacingProfile,
  GuiBorderProfile,
  GuiShadowProfile,
  GuiButtonSounds,
  GuiTextAlignment,
  GuiClipCommand,
  GuiControlCommand,
  GuiControlKindCode,
  GuiScrollBarMode,
  GuiBitmapButtonTextures,
  GuiItemId,
  GuiArrayItem,
  GuiTreeNode,
  GuiDrawingCommand,
  GuiDrawingLine,
  GuiDrawingRect,
  GuiDrawingCircle,
  GuiDrawingText,
  GuiDrawingImage,
  GuiDrawingPolyline,
} from './gui';
export { ColyseusClient, Room } from './colyseus';
export type { RoomRequestOptions, RoomRequestCallbacks, ColyseusError, RoomJoinCallbacks } from './colyseus';
